name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - run: npm install
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.507'
    - run: clojure -A:shadow-cljs -v release chat
    - uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: "fir-rtc-b4da8"
